Repository midwayjs/midway, pull requests merged in 2022-12, with the labels that each got.

#2549 docs(site): update awesome_midway.md
  site/docs/awesome_midway.md
  site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
Labels: pr: documentation

#2399 feat(casbin): add-casbin-watcher-and-fix-type
  packages/casbin/src/enforcer.service.ts
  packages/casbin/src/interface.ts
Labels: pr: polish

#2526 fix: add default job options when create queue
  packages/bull/src/decorator.ts
  packages/bull/src/framework.ts
Labels: pr: bug fix

#2566 fix: captcha store prefix
  packages/captcha/src/service.ts
Labels: pr: bug fix

#2576 fix: event not format in faas
  packages-serverless/midway-fc-starter/src/index.ts
  packages/faas/src/framework.ts
  packages/faas/src/interface.ts
  packages/faas/test/new.test.ts
  packages/mock/src/creator.ts
Labels: pr: bug fix

#2574 feat: add @injectClient for service factory
  packages/core/src/common/serviceFactory.ts
  packages/core/src/decorator/common/inject.ts
  packages/core/src/decorator/constant.ts
  packages/core/src/interface.ts
  packages/core/src/service/frameworkService.ts
  packages/core/test/baseFramework.test.ts
  packages/core/test/fixtures/base-app-service-factory-inject/package.json
  packages/core/test/fixtures/base-app-service-factory-inject/src/configuration.ts
Labels: pr: new feature

#2573 fix: ignore backup egg logger error
  packages/web/src/logger.ts
Labels: pr: bug fix

#2560 feat: support casbin watcher
  packages/casbin-redis-adapter/package.json
  packages/casbin-redis-adapter/src/index.ts
  packages/casbin-redis-adapter/src/watcher.ts
  packages/casbin-redis-adapter/test/fixtures/base-app/src/config/config.default.ts
  packages/casbin-redis-adapter/test/fixtures/base-app/src/home.controller.ts
  packages/casbin-redis-adapter/test/index.test.ts
  packages/casbin/src/enforcer.service.ts
  packages/casbin/src/interface.ts
  packages/casbin/src/watcher.ts
  packages/core/test/decorator/index.test.ts
  packages/redis/src/manager.ts
  scripts/build.sh
Labels: pr: new feature

#2551 feat: support socket.io sticky session
  packages/bootstrap/package.json
  packages/bootstrap/src/bootstrap.ts
  packages/bootstrap/src/index.ts
  packages/bootstrap/src/interface.ts
  packages/bootstrap/src/manager/base.ts
  packages/bootstrap/src/manager/cp.ts
  packages/bootstrap/src/manager/thread.ts
  packages/bootstrap/src/sticky.ts
  packages/bootstrap/src/util.ts
  packages/bootstrap/test/bootstrap.test.ts
  packages/bootstrap/test/fixtures/cluster-app/bootstrap.js
  packages/bootstrap/test/fixtures/cluster-app/package.json
  packages/bootstrap/test/fixtures/cluster-app/src/config/config.default.ts
  packages/bootstrap/test/fixtures/cluster-app/src/configuration.ts
  packages/bootstrap/test/fixtures/cluster-app/src/controller/home.ts
  packages/bootstrap/test/fixtures/cluster-app/src/index.ts
  packages/bootstrap/test/fixtures/cluster-app/src/service/remoteConfigService.ts
  packages/bootstrap/test/fixtures/cluster-app/src/ws/api.ts
  packages/bootstrap/test/fixtures/mix-app/bootstrap.js
  packages/bootstrap/test/fork/case-cp/worker-1.ts
  packages/bootstrap/test/fork/case-cp/worker-2.ts
  packages/bootstrap/test/fork/case-cp/worker-3.ts
  packages/bootstrap/test/fork/case-thread/worker-1.ts
  packages/bootstrap/test/fork/case-thread/worker-2.ts
  packages/bootstrap/test/fork/case-thread/worker-3.ts
  packages/bootstrap/test/fork/cp.test.ts
  packages/bootstrap/test/fork/thread.test.ts
Labels: pr: new feature

#2535 chore: sync code from https://github.com/midwayjs/fork-dep-monitor/pu…
  packages/web-koa/index.d.ts
Labels: pr: maintenance

#2534 chore: sync code from https://github.com/midwayjs/fork-dep-monitor/pu…
  packages/core/src/util/camelCase.ts
  packages/core/test/decorator/util/camelCase.test.ts
Labels: pr: maintenance

#2533 fix: glob support more wildcard string
  packages/core/src/common/dataSourceManager.ts
  packages/core/test/common/dataSourceManager.test.ts
  packages/core/test/common/glob_dir_pattern/c.js
  packages/core/test/common/glob_dir_pattern/e.entity.ts
Labels: pr: bug fix

#2540 perf(core): reuse methodDecoratorHandler
  packages/core/src/service/decoratorService.ts
Labels: pr: performance

#2580 chore: add cluster exit binding
  packages/bootstrap/src/manager/base.ts
  packages/bootstrap/src/manager/thread.ts
  packages/bootstrap/test/fixtures/cluster-app/src/configuration.ts
  packages/bootstrap/test/fork/cp.test.ts
  packages/bootstrap/test/fork/thread.test.ts
Labels: pr: polish

#2582 fix: merge queue options and job options
  packages/bull/index.d.ts
  packages/bull/src/config/config.default.ts
Labels: pr: bug fix

#2547 fix: swagger query object
  packages/swagger/src/swaggerExplorer.ts
Labels: pr: bug fix

#2587 feat: support typeorm migrate cli
  packages/axios/package.json
  packages/axios/test/factory.test.ts
  packages/axios/test/index.test.ts
  packages/typeorm/cli.js
  packages/typeorm/package.json
Labels: pr: polish

#2588 fix: add ts-node run in migrate
  packages/typeorm/cli.js
Labels: pr: bug fix

#2592 fix: static with cors
  packages/cross-domain/src/middleware/cors.ts
  packages/cross-domain/src/middleware/jsonp.ts
  packages/http-proxy/src/middleware.ts
  packages/static-file/src/configuration.ts
Labels: pr: bug fix

#2594 fix: bull read new config after config load
  packages/bull/src/configuration.ts
  packages/bull/src/framework.ts
  packages/bull/test/fixtures/base-app-redis/src/configuration.ts
Labels: pr: bug fix

#2602 fix: use lazy function to provide type
  packages/swagger/src/interfaces/index.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/parser.test.ts
Labels: pr: bug fix

#2607 chore: add apiResponse case
  packages/swagger/test/__snapshots__/index.test.ts.snap
  packages/swagger/test/fixtures/issue2603/package.json
  packages/swagger/test/fixtures/issue2603/src/configuration.ts
  packages/swagger/test/fixtures/issue2603/src/dto.ts
  packages/swagger/test/fixtures/issue2603/src/test.controller.ts
  packages/swagger/test/index.test.ts
  packages/swagger/test/parser.test.ts
Labels: pr: internal
