Repository midwayjs/midway, pull requests merged in 2022-11, with the labels that each got.

#2460 fix: remove dependencies and avoid multi-instance in npm
  packages/sequelize/package.json
Labels: pr: dependencies

#2466 fix: type property replace ts type
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/parser.test.ts
Labels: pr: bug fix

#2465 docs: Add grafana to docker-compose.yml
  site/docs/extensions/prometheus.md
Labels: pr: documentation

#2470 docs: update deployment.md
  site/docs/deployment.md
Labels: pr: documentation

#2464 fix: getServerlessInstance add ctx hook
  .github/workflows/benchmark.yml
  packages-serverless/midway-fc-starter/src/index.ts
  packages-serverless/midway-fc-starter/src/mock.ts
  packages/faas/src/framework.ts
  packages/faas/src/interface.ts
  packages/faas/test/fixtures/base-app-event-middleware/src/func.ts
  packages/faas/test/new.test.ts
  packages/mock/src/creator.ts
  packages/mock/src/mock.ts
  scripts/benchmark/benchmark.mjs
Labels: pr: bug fix

#2469 fix: swagger ui favicon output
  packages/swagger/src/swaggerMiddleware.ts
Labels: pr: bug fix

#2472 chore: pin cos version
  packages/cos/package.json
Labels: pr: dependencies

#2477 fix: duplicate mongoose import
  packages/typegoose/index.d.ts
Labels: pr: bug fix

#2478 docs: fix serverless_yml link path
  site/docs/serverless/serverless_dev.md
Labels: pr: documentation

#2479 docs(orm): add OrmConnectionHook example for legacy orm.md
  site/docs/legacy/orm.md
Labels: pr: documentation

#2485 chore: add job typings export
  packages/bull/index.d.ts
Labels: pr: polish

#2487 docs(site): add a throttler like @nestjs/throttler to awesome_midway.md
  site/docs/awesome_midway.md
Labels: pr: documentation

#2483 fix: noise and size support
  packages/captcha/src/config/config.default.ts
  packages/captcha/src/interface.ts
  packages/captcha/src/service.ts
  packages/captcha/test/fixtures/koa/src/configuration.ts
  site/docs/extensions/captcha.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/captcha.md
Labels: pr: bug fix

#2489 docs(site): fix midway-throttler url link in awesome_midway.md
  site/docs/awesome_midway.md
  site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
Labels: pr: documentation

#2502 docs: fix remoteConfig in Life Cycle
  site/docs/env_config.md
  site/i18n/en/docusaurus-plugin-content-docs/current/env_config.md
Labels: pr: documentation

#2503 chore: update faas method
  packages-serverless/midway-fc-starter/src/index.ts
  packages/faas/src/framework.ts
  packages/faas/src/interface.ts
  packages/faas/test/new.test.ts
  packages/mock/src/creator.ts
Labels: pr: internal

#2493 fix: bull exports and typings
  packages/bull/src/framework.ts
  packages/bull/src/index.ts
  packages/bull/src/interface.ts
  site/docs/extensions/bull.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/bull.md
Labels: pr: bug fix

#2504 fix: remove router cache and fix issue #2319
  packages/core/src/service/webRouterService.ts
  packages/core/test/fixtures/issue-2319/package.json
  packages/core/test/fixtures/issue-2319/src/configuration.ts
  packages/core/test/service/__snapshots__/webRouterService.test.ts.snap
  packages/core/test/service/webRouterService.test.ts
Labels: pr: bug fix

#2498 feat: add injectDataSource for mikro/typeorm/sequelize
  packages/core/src/common/dataSourceManager.ts
  packages/core/test/common/dataSourceManager.test.ts
  packages/mikro/src/configuration.ts
  packages/mikro/src/decorator.ts
  packages/mikro/test/fixtures/base-fn-origin/src/config/config.default.ts
  packages/mikro/test/fixtures/base-fn-origin/src/configuration.ts
  packages/sequelize/src/configuration.ts
  packages/sequelize/src/decorator.ts
  packages/sequelize/test/fixtures/sequelize-new/src/config/config.default.ts
  packages/sequelize/test/fixtures/sequelize-new/src/configuration.ts
  packages/typeorm/src/configuration.ts
  packages/typeorm/src/decorator.ts
  packages/typeorm/test/fixtures/base-fn-origin/src/config/config.default.ts
  packages/typeorm/test/fixtures/base-fn-origin/src/configuration.ts
Labels: pr: new feature

#2482 feat: serviceFactory support default client name
  packages/axios/src/serviceManager.ts
  packages/core/src/common/serviceFactory.ts
  packages/core/src/interface.ts
  packages/core/test/common/serviceFactory.test.ts
  packages/cos/src/manager.ts
  packages/oss/src/manager.ts
  packages/redis/src/manager.ts
  packages/tablestore/src/manager.ts
Labels: pr: new feature

#2481 feat: add etcd component
  .github/workflows/nodejs.yml
  packages/etcd/README.md
  packages/etcd/index.d.ts
  packages/etcd/jest.config.js
  packages/etcd/jest.setup.js
  packages/etcd/package.json
  packages/etcd/src/config.default.ts
  packages/etcd/src/configuration.ts
  packages/etcd/src/index.ts
  packages/etcd/src/manager.ts
  packages/etcd/test/fixtures/base-app-single-client/package.json
  packages/etcd/test/fixtures/base-app-single-client/src/config.default.ts
  packages/etcd/test/fixtures/base-app-single-client/src/configuration.ts
  packages/etcd/test/index.test.ts
  packages/etcd/tsconfig.json
Labels: pr: new feature

#2505 fix: windows entity glob and close #2488
  packages/core/src/common/dataSourceManager.ts
Labels: pr: bug fix

#2506 perf: remove babel isClass check
  packages/core/src/util/types.ts
Labels: pr: performance

#2512 fix: etcd support default instance name
  packages/etcd/src/manager.ts
Labels: pr: bug fix

#2514 doc(consul.md): fix port type error
  site/docs/extensions/consul.md
Labels: pr: documentation

#2515 docs(site): update awesome_midway.md
  site/docs/awesome_midway.md
  site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
Labels: pr: documentation

#2516 docs: update the configuration description of AccessKey
  site/docs/serverless/aliyun_faas.md
Labels: pr: documentation

#2525 fix: sequelize inject data source forgot to export
  packages/sequelize/src/index.ts
Labels: pr: bug fix

#2518 fix: swagger global prefix without path
  packages/swagger/src/configuration.ts
Labels: pr: polish

#2538 fix: data source find sequence
  packages/mikro/src/configuration.ts
  packages/sequelize/src/configuration.ts
  packages/typeorm/src/configuration.ts
Labels: pr: bug fix
