Repository midwayjs/midway, pull requests merged in 2023-02, with the labels that each got.

#2699 fix: repair the impact of JSONP on normal requests(#2692)
  packages/cross-domain/src/jsonp.ts
  packages/cross-domain/test/express.test.ts
  packages/cross-domain/test/koa.test.ts
Labels: pr: bug fix

#2701 feat: add ctx.traceId
  packages/otel/index.d.ts
  packages/otel/src/configuration.ts
  packages/otel/src/service.ts
  packages/otel/test/fixtures/base-app/src/user.service.ts
  packages/otel/test/index.test.ts
Labels: pr: polish

#2704 fix: typeorm logging property
  packages/typeorm/src/dataSourceManager.ts
Labels: pr: bug fix

#2703 fix: @valid with other decorator
  packages/core/src/service/decoratorService.ts
  packages/validate/src/constants.ts
  packages/validate/src/decorator/rule.ts
  packages/validate/test/check.test.ts
Labels: pr: bug fix

#2697 fix: RouterService match router method all
  packages/core/src/service/webRouterService.ts
  packages/core/test/service/webRouterService.test.ts
Labels: pr: bug fix

#2707 docs(site): add contribution leaderboard badge into README file.
  README.en-US.md
  README.md
Labels: pr: internal

#2708 feat: add web param optional
  packages/core/src/decorator/web/paramMapping.ts
  packages/core/test/decorator/web/__snapshots__/paramMapping.test.ts.snap
  packages/core/test/decorator/web/paramMapping.test.ts
  packages/decorator/test/web/__snapshots__/paramMapping.test.ts.snap
  packages/faas/src/decorator.ts
  packages/validate/src/decorator/valid.ts
Labels: pr: polish

#2715 docs(site): update validate.md
  site/docs/extensions/validate.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/validate.md
Labels: pr: dependencies

#2714 fix(validate): export ParsePipe from pipe.ts
  packages/validate/src/pipe.ts
Labels: pr: bug fix

#2717 feat: support buffer response
  packages/faas/src/framework.ts
  packages/faas/src/interface.ts
  packages/faas/src/starter.ts
  packages/faas/test/fixtures/base-app-response-buffer/package.json
  packages/faas/test/fixtures/base-app-response-buffer/src/configuration.ts
  packages/faas/test/fixtures/base-app-response-buffer/src/func.ts
  packages/faas/test/fixtures/base-app-response-buffer/src/index.ts
  packages/faas/test/new.test.ts
Labels: pr: polish

#2719 fix: node 12 fs promise
  packages/mock/src/utils.ts
Labels: pr: polish

#2727 doc:custom_error.md fix import
  site/docs/custom_error.md
Labels: pr: documentation

#2733 chore: add generalization type
  packages/core/src/util/httpclient.ts
Labels: pr: polish

#2732 fix: func name set
  packages/core/src/service/slsFunctionService.ts
  packages/faas/src/framework.ts
Labels: pr: bug fix

#2731 docs: fix pipe valid
  site/docs/extensions/validate.md
Labels: pr: documentation

#2720 fix: bull add default job options in decorator will be overriding args
  packages/bull/src/framework.ts
Labels: pr: bug fix

#2728 chore: update codedye
  packages/code-dye/README.md
  packages/code-dye/src/config/config.default.ts
  packages/code-dye/src/configuration.ts
  packages/code-dye/src/interface.ts
  site/docs/extensions/code_dye.md
  site/docs/sidebars.json
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/code_dye.md
Labels: pr: polish

#2734 fix: function meta name
  packages/core/src/service/slsFunctionService.ts
  packages/core/test/fixtures/app-with-function-name/package.json
  packages/core/test/fixtures/app-with-function-name/src/configuration.ts
  packages/core/test/service/slsFunctionService.test.ts
  packages/web/src/base.ts
  packages/web/src/decorator.ts
  packages/web/src/interface.ts
  packages/web/src/utils.ts
  packages/web/test/feature.test.ts
  packages/web/test/fixtures/feature/base-app-run-in-agent/package.json
  packages/web/test/fixtures/feature/base-app-run-in-agent/src/config/config.default.ts
  packages/web/test/fixtures/feature/base-app-run-in-agent/src/config/config.unittest.ts
  packages/web/test/fixtures/feature/base-app-run-in-agent/src/configuration.ts
  packages/web/test/fixtures/feature/base-app-run-in-agent/src/controller/api.ts
Labels: pr: bug fix

#2738 feat: support stream response
  .gitignore
  packages-serverless/faas-typings/typings/common.ts
  packages-serverless/serverless-http-parser/src/http/res.ts
  packages-serverless/serverless-http-parser/src/interface.ts
  packages-serverless/serverless-http-parser/src/response.ts
  packages-serverless/serverless-http-parser/test/index.test.ts
  packages-serverless/serverless-http-parser/test/resource/source.json
  packages/faas/src/framework.ts
  packages/faas/src/interface.ts
  packages/http-proxy/src/middleware.ts
  packages/mock/src/creator.ts
Labels: pr: polish

#2747 fix: joi version for node 12/14
  packages/validate/package.json
Labels: pr: bug fix

#2748 fix: wrong proxy namespace
  packages/http-proxy/src/configuration.ts
Labels: pr: bug fix

#2739 fix: cross domain with options request
  packages/cross-domain/src/middleware/cors.ts
  packages/cross-domain/test/faas.test.ts
  packages/cross-domain/test/fixtures/faas/f.yml
  packages/cross-domain/test/fixtures/faas/src/configuration.ts
  packages/faas/src/framework.ts
Labels: pr: bug fix

#2757 fix: mock buffer base64 response
  packages/mock/src/creator.ts
Labels: pr: bug fix

#2758 chore: add context.streaming api for streaming api
  packages-serverless/faas-typings/typings/common.ts
  packages-serverless/serverless-http-parser/src/context.ts
  packages-serverless/serverless-http-parser/src/http/res.ts
  packages-serverless/serverless-http-parser/test/index.test.ts
Labels: pr: bug fix

#2759 fix: set streaming property first
  packages-serverless/serverless-http-parser/src/http/res.ts
Labels: pr: bug fix

#2773 docs(site): update validate.md
  site/docs/extensions/validate.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/validate.md
Labels: pr: documentation
