Repository midwayjs/midway, pull requests merged in 2023-08, with the labels that each got.

#3126 fix: swagger @ApiHeader @ApiHeaders only read one header
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/index.test.ts.snap
  packages/swagger/test/fixtures/cats/src/cats.controller.ts
Labels: pr: bug fix

#3127 feat: expose more APIs from axios
  packages/axios/src/interface.ts
  packages/axios/src/serviceManager.ts
  packages/axios/test/index.test.ts
  site/docs/extensions/axios.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/axios.md
Labels: pr: polish

#3122 feat: add swagger operationId
  packages/swagger/src/interfaces/index.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/index.test.ts.snap
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/index.test.ts
  site/docs/extensions/swagger.md
Labels: pr: polish

#3130 fix(http-proxy): readableStream.pipe(res) and res.on('finish')
  packages/http-proxy/src/middleware.ts
Labels: pr: bug fix

#3144 fix: bull logger typo
  packages/bull/src/config/config.default.ts
  packages/cron/src/configuration.ts
Labels: pr: bug fix

#3132 feat: expose native OSS from package
  packages/oss/src/interface.ts
Labels: pr: polish

#3114 feat: add InjectEntityManager decorator for MikroORM and upgrade document
  packages/mikro/src/configuration.ts
  packages/mikro/src/decorator.ts
  packages/mikro/test/fixtures/base-fn-origin/src/configuration.ts
  site/docs/extensions/mikro.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/mikro.md
Labels: pr: polish

#3133 feat: add ctx.forward api
  packages/web-koa/index.d.ts
  packages/web-koa/src/framework.ts
  packages/web-koa/test/fixtures/base-app-forward/package.json
  packages/web-koa/test/fixtures/base-app-forward/src/configuration.ts
  packages/web-koa/test/index.test.ts
  packages/web/app/extend/context.js
  packages/web/index.d.ts
  packages/web/test/feature.test.ts
  packages/web/test/fixtures/feature/base-app-forward/package.json
  packages/web/test/fixtures/feature/base-app-forward/src/config/config.default.ts
  packages/web/test/fixtures/feature/base-app-forward/src/configuration.ts
  packages/web/test/fixtures/feature/base-app-forward/src/controller/api.ts
Labels: pr: new feature

#3110 feat: support all http methods
  packages/core/src/util/httpclient.ts
  packages/core/test/util.ts
  packages/core/test/util/httpclient.test.ts
Labels: pr: new feature

#3085 feat: upgrade bull-board v5.6.0
  packages/bull-board/index.d.ts
  packages/bull-board/package.json
  packages/bull-board/src/adapter.ts
  packages/bull-board/src/board.middleware.ts
  packages/bull-board/src/configuration.ts
  packages/bull-board/src/index.ts
  packages/bull-board/src/interface.ts
Labels: pr: dependencies, pr: new feature

#2961 feat: add getApp and getScope api
  packages/core/src/baseFramework.ts
  packages/core/src/constants.ts
  packages/core/src/context/container.ts
  packages/core/src/context/managedResolverFactory.ts
  packages/core/src/interface.ts
  packages/core/test/baseFramework.test.ts
  packages/core/test/context/requestContainer.test.ts
Labels: pr: new feature

#3109 refactor(consul): consul's implementation was refactored
  packages/consul/src/config/config.default.ts
  packages/consul/src/configuration.ts
  packages/consul/src/consul.service.ts
  packages/consul/src/controller/consul.ts
  packages/consul/src/index.ts
  packages/consul/src/interface.ts
  packages/consul/src/lib/balancer.ts
  packages/consul/src/lib/provider.ts
  packages/consul/src/service/balancer.ts
  packages/consul/test/fixtures/base-app/src/config/config.default.ts
  packages/consul/test/fixtures/base-app/src/configuration.ts
  packages/consul/test/fixtures/base-app/src/controller/test.ts
  packages/consul/test/fixtures/mock.data.ts
  packages/consul/test/index.test.ts
  packages/consul/test/mock.ts
  packages/consul/usage.md
  site/docs/extensions/consul.md
Labels: pr: breaking change, pr: new feature

#3087 feat(deps): support leoric as model layer
  packages/core/src/common/dataSourceManager.ts
  packages/core/src/index.ts
  packages/core/src/interface.ts
  packages/leoric/README.md
  packages/leoric/index.d.ts
  packages/leoric/jest.config.js
  packages/leoric/jest.setup.js
  packages/leoric/package.json
  packages/leoric/src/configuration.ts
  packages/leoric/src/dataSourceManager.ts
  packages/leoric/src/decorator.ts
  packages/leoric/src/index.ts
  packages/leoric/src/interface.ts
  packages/leoric/test/dumpfile.sql
  packages/leoric/test/fixtures/basic/package.json
  packages/leoric/test/fixtures/basic/src/config/config.default.ts
  packages/leoric/test/fixtures/basic/src/configuration.ts
  packages/leoric/test/fixtures/basic/src/model/post.ts
  packages/leoric/test/fixtures/basic/src/model/user.ts
  packages/leoric/test/fixtures/basic/src/service/user.ts
  packages/leoric/test/index.test.ts
  packages/leoric/tsconfig.json
Labels: pr: new feature

#3164 chore(decorator): opt code in serverlessTrigger
  packages/core/src/decorator/faas/serverlessTrigger.ts
Labels: pr: maintenance

#3168 fix: import json not support under node v16
  packages/core/src/util/index.ts
Labels: pr: bug fix

#3171 fix: load file missing file prefix under windows
  packages/core/src/util/index.ts
  packages/core/test/util/util.test.ts
Labels: pr: bug fix

#3175 fix: use original method name
  packages/core/src/setup.ts
  packages/web/src/cluster.ts
Labels: pr: bug fix

#3166 docs: add document for esm version
  site/blog/2023-08-13-remove-node-14-ci.md
  site/blog/2023-08-14-release-3.12.md
  site/docs/container.md
  site/docs/controller.md
  site/docs/esm.md
  site/docs/req_res_app.md
  site/docs/sidebars.json
  site/docusaurus.config.js
  site/i18n/en/docusaurus-plugin-content-docs/current/container.md
  site/i18n/en/docusaurus-plugin-content-docs/current/controller.md
  site/i18n/en/docusaurus-plugin-content-docs/current/esm.md
  site/i18n/en/docusaurus-plugin-content-docs/current/req_res_app.md
  site/lib/navbar.js
Labels: pr: documentation
