Repository midwayjs/midway, pull requests merged in 2023-04, with the labels that each got.

#2840 docs: update kafka disconnect
  site/docs/extensions/kafka.md
Labels: pr: documentation

#2841 chore(core): add boolean property JoinPoint['proceedIsAsyncFunction']
  packages/core/src/interface.ts
  packages/core/src/service/aspectService.ts
  packages/core/test/service/aspectService.test.ts
Labels: pr: polish

#2842 feat: add queueOptions to the @Processor decorator
  packages/bull/src/decorator.ts
  packages/bull/src/framework.ts
Labels: pr: polish

#2838 chore: more debug info
  packages/core/src/decorator/decoratorManager.ts
  packages/core/src/service/middlewareService.ts
  packages/core/src/util/pathFileUtil.ts
Labels: pr: internal

#2850 fix: fixed missing initial messages (#2847)
  packages/socketio/src/framework.ts
  packages/socketio/test/fixtures/base-app-middleware/src/middleware/conn.middleware.ts
Labels: pr: bug fix

#2854 fix: fixed duplicated OnWSConnection
  packages/socketio/src/framework.ts
Labels: pr: bug fix

#2857 fix: change for support worker
  packages/mock/src/utils.ts
Labels: pr: bug fix

#2858 docs(site): update awesome_midway.md
  site/docs/awesome_midway.md
  site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
Labels: pr: documentation

#2859 fix(deps): update dependency casbin to v5.26.1
  packages/casbin-redis-adapter/package.json
  packages/casbin-redis-adapter/test/fixtures/base-app/src/configuration.ts
  packages/casbin-typeorm-adapter/package.json
  packages/casbin-typeorm-adapter/test/fixtures/base-app/src/configuration.ts
  packages/casbin/package.json
Labels: pr: dependencies

#2885 fix: bootstrap test case
  .eslintrc.json
  packages/bootstrap/package.json
  packages/bootstrap/test/fork/case-cp/worker-2.ts
  packages/bootstrap/test/fork/cp.test.ts
  packages/core/src/common/dataSourceManager.ts
  packages/core/src/interface.ts
  packages/core/test/common/__snapshots__/dataSourceManager.test.ts.snap
  packages/core/test/common/abc/ppp/d.ts
  packages/core/test/common/abc/ppp/e.ts
  packages/core/test/common/dataSourceManager.test.ts
  packages/otel/package.json
  renovate.json
Labels: pr: bug fix

#2899 feat: support app enable ssl custom certificate in dev mode
  packages-legacy/serverless-app/src/framework.ts
  packages-legacy/serverless-app/src/interface.ts
Labels: pr: polish

#2907 fix: compatible typeorm objectId changes
  packages-legacy/orm/package.json
  packages/casbin-typeorm-adapter/package.json
  packages/casbin-typeorm-adapter/src/adapter.ts
  packages/casbin-typeorm-adapter/src/casbinMongoRule.ts
  packages/typeorm/package.json
Labels: pr: bug fix

#2905 fix: createServerlessApp baseDir with undefined
  packages/mock/src/creator.ts
Labels: pr: bug fix

#2906 feat: add more http options
  packages/core/src/util/httpclient.ts
Labels: pr: polish
