Repository midwayjs/midway, pull requests merged in 2023-11, with the labels that each got.

#3382 fix(swagger): api property should support $ref
  packages/swagger/src/decorators/api-property.decorator.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/index.test.ts.snap
  packages/swagger/test/fixtures/cats/src/entities/cat.entity.ts
  packages/swagger/test/fixtures/cats/src/entities/utils.ts
  packages/swagger/test/fixtures/cats/tsconfig.json
  packages/swagger/test/index.test.ts
  site/docs/extensions/swagger.md
Labels: pr: bug fix

#3389 fix: catch error when bull framework create service
  packages/bull/src/framework.ts
  packages/bull/test/fixtures/base-app-error-out-of-job/package.json
  packages/bull/test/fixtures/base-app-error-out-of-job/src/configuration.ts
  packages/bull/test/fixtures/base-app-error-out-of-job/src/task/hello.task.ts
  packages/bull/test/index.test.ts
Labels: type: bug

#3417 docs(session): Supplementary explanation on SameSite = None
  site/docs/cookie_session.md
  site/i18n/en/docusaurus-plugin-content-docs/current/cookie_session.md
Labels: pr: documentation

#3422 fix: static file component namespace
  packages/static-file/src/configuration.ts
Labels: pr: bug fix

#3402 fix: context.state property override when context typings merge
  packages/faas/src/interface.ts
  packages/passport/index.d.ts
  packages/web-koa/index.d.ts
  packages/web-koa/src/interface.ts
  packages/web/index.d.ts
  packages/web/src/interface.ts
  site/docs/extensions/egg.md
  site/docs/extensions/koa.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/egg.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/koa.md
Labels: pr: polish

#3391 feat: add enable config for http-proxy
  packages/http-proxy/src/config/config.default.ts
  packages/http-proxy/src/configuration.ts
  packages/http-proxy/src/interface.ts
Labels: pr: polish

#3381 feat: add build-in healthService
  packages/core/src/config/config.default.ts
  packages/core/src/error/framework.ts
  packages/core/src/index.ts
  packages/core/src/interface.ts
  packages/core/src/service/healthService.ts
  packages/core/src/service/lifeCycleService.ts
  packages/core/src/setup.ts
  packages/core/src/util/index.ts
  packages/core/test/feature.test.ts
  packages/core/test/fixtures/app-with-health-check-empty/package.json
  packages/core/test/fixtures/app-with-health-check-empty/src/configuration.ts
  packages/core/test/fixtures/app-with-health-check/package.json
  packages/core/test/fixtures/app-with-health-check/src/configuration.ts
  packages/core/test/util/util.test.ts
  packages/info/test/__snapshots__/index.test.ts.snap
  site/docs/built_in_service.md
  site/i18n/en/docusaurus-plugin-content-docs/current/built_in_service.md
Labels: pr: new feature

#3247 fix: sort with imports sequence before framework run
  packages/core/src/service/frameworkService.ts
Labels: pr: bug fix

#3261 feat: config separated options for verify & decode and bug fixes
  packages/jwt/index.d.ts
  packages/jwt/package.json
  packages/jwt/src/jwt.ts
  packages/jwt/test/fixtures/base-app-2/package.json
  packages/jwt/test/fixtures/base-app-2/src/configuration.ts
  packages/jwt/test/index.test.ts
Labels: pr: new feature

#3425 chore: export default jwt instance
  packages/jwt/index.d.ts
  packages/jwt/src/index.ts
  packages/jwt/src/interface.ts
  packages/jwt/src/jwt.ts
  packages/jwt/test/index.test.ts
  site/docs/extensions/jwt.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/jwt.md
Labels: pr: polish

#3427 fix: missing default logger dir when cluster mode
  packages/web/src/logger.ts
Labels: pr: bug fix

#3428 fix: core logger missing file log name
  packages/web/src/logger.ts
Labels: pr: bug fix

#3443 docs(jwt): Fix a bug in the documentation example where `jwtService` is not retrieved from `this`.
  site/docs/extensions/jwt.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/jwt.md
Labels: pr: documentation

#3448 fix: parsing array of size > 20 in query (#3447)
  packages/web/app/extend/request.js
  packages/web/src/interface.ts
  packages/web/test/feature.test.ts
  packages/web/test/fixtures/feature/base-app-query-parser/src/config/config.default.ts
  site/docs/extensions/egg.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/egg.md
Labels: pr: bug fix

#3455 fix(web): default app logger name error in cluster mode
  packages/web/src/logger.ts
  site/docs/logger.md
  site/i18n/en/docusaurus-plugin-content-docs/current/logger.md
Labels: pr: bug fix

#3456 fix: web default config
  packages/web/src/config/config.default.ts
Labels: pr: bug fix
