Repository midwayjs/midway, pull requests merged in 2023-07, with the labels that each got.

#3058 docs(site): update how_to_install_nodejs.md
  site/docs/how_to_install_nodejs.md
  site/i18n/en/docusaurus-plugin-content-docs/current/how_to_install_nodejs.md
Labels: pr: documentation

#3061 chore: remove function typings
  packages/swagger/src/interfaces/index.ts
  packages/validate/src/dtoHelper.ts
Labels: pr: internal

#3070 chore: update lerna to v7
  .github/workflows/benchmark.yml
  .github/workflows/nodejs.yml
  .github/workflows/precheck.yml
  .github/workflows/presite.yml
  .github/workflows/site.yml
  nx.json
  package.json
  packages/info/test/__snapshots__/index.test.ts.snap
  packages/info/test/index.test.ts
  packages/mock/src/creator.ts
  packages/mock/src/interface.ts
  packages/mock/test/new.test.ts
  scripts/install_npm.sh
Labels: pr: dependencies

#3069 fix(consul): Adjust the application registration logic to obtain consul instances when the application only acts as a service caller and does not register.
  packages/consul/src/configuration.ts
Labels: pr: bug fix

#3077 fix: bull typings in interop mode
  package.json
  packages/bull/src/framework.ts
Labels: pr: bug fix

#3076 fix: makeHttpRequest failed when post with custom headers
  packages/core/src/util/httpclient.ts
  packages/core/test/util/httpclient.test.ts
Labels: pr: bug fix

#3032 feat(deps): support leoric as model layer
  packages/leoric/README.md
  packages/leoric/index.d.ts
  packages/leoric/jest.config.js
  packages/leoric/jest.setup.js
  packages/leoric/package.json
  packages/leoric/src/config/config.default.ts
  packages/leoric/src/configuration.ts
  packages/leoric/src/dataSourceManager.ts
  packages/leoric/src/decorator.ts
  packages/leoric/src/index.ts
  packages/leoric/src/interface.ts
  packages/leoric/test/dumpfile.sql
  packages/leoric/test/fixtures/basic/package.json
  packages/leoric/test/fixtures/basic/src/config/config.default.ts
  packages/leoric/test/fixtures/basic/src/configuration.ts
  packages/leoric/test/fixtures/basic/src/model/post.ts
  packages/leoric/test/fixtures/basic/src/model/user.ts
  packages/leoric/test/fixtures/basic/src/service/user.ts
  packages/leoric/test/index.test.ts
  packages/leoric/tsconfig.json
Labels: pr: polish
