Repository midwayjs/midway, pull requests merged in 2023-03, with the labels that each got.

#2788 chore: update debugger output
  packages/core/src/context/container.ts
  packages/core/src/setup.ts
  packages/core/src/util/index.ts
Labels: pr: internal

#2765 fix: content-type set by headers options
  packages/core/src/util/httpclient.ts
Labels: pr: bug fix

#2764 fix: mock service inited will be before lifecycle
  packages/core/src/service/mockService.ts
  packages/core/src/setup.ts
Labels: pr: bug fix

#2806 chore: add MIDWAY_SOURCE_DIR for egg
  packages/web/src/utils.ts
Labels: pr: internal

#2807 fix: egg missing export decorator
  packages/web/src/index.ts
Labels: pr: bug fix

#2805 feat: support match and ignore property with array
  packages/core/src/interface.ts
  packages/core/src/service/middlewareService.ts
  packages/core/src/util/index.ts
  packages/core/test/service/middlewareService.test.ts
Labels: pr: new feature

#2771 feat: add cron component
  packages/cron/README.md
  packages/cron/index.d.ts
  packages/cron/jest.config.js
  packages/cron/jest.setup.js
  packages/cron/package.json
  packages/cron/src/configuration.ts
  packages/cron/src/constants.ts
  packages/cron/src/decorator.ts
  packages/cron/src/framework.ts
  packages/cron/src/index.ts
  packages/cron/src/interface.ts
  packages/cron/test/fixtures/base-app-err/package.json
  packages/cron/test/fixtures/base-app-err/src/configuration.ts
  packages/cron/test/fixtures/base-app-err/src/task/hello.task.ts
  packages/cron/test/fixtures/base-app/package.json
  packages/cron/test/fixtures/base-app/src/configuration.ts
  packages/cron/test/fixtures/base-app/src/task/hello.task.ts
  packages/cron/test/index.test.ts
  packages/cron/tsconfig.json
Labels: pr: new feature

#2740 feat: tags component
  packages/tags/CHANGELOG.md
  packages/tags/README.md
  packages/tags/index.d.ts
  packages/tags/jest.config.js
  packages/tags/jest.setup.js
  packages/tags/package.json
  packages/tags/src/configuration.ts
  packages/tags/src/dialect/index.ts
  packages/tags/src/dialect/memory.ts
  packages/tags/src/dialect/mysql.ts
  packages/tags/src/error.ts
  packages/tags/src/index.ts
  packages/tags/src/interface.ts
  packages/tags/src/manager.ts
  packages/tags/src/service.ts
  packages/tags/src/utils.ts
  packages/tags/test/fixtures/base-app/package.json
  packages/tags/test/fixtures/base-app/src/config.default.ts
  packages/tags/test/fixtures/base-app/src/configuration.ts
  packages/tags/test/fixtures/mysql/package.json
  packages/tags/test/fixtures/mysql/src/config.default.ts
  packages/tags/test/fixtures/mysql/src/configuration.ts
  packages/tags/test/memory.test.ts
  packages/tags/test/mysql.test.ts
  packages/tags/tsconfig.json
  packages/upload/src/error.ts
  site/docs/extensions/tags.md
  site/docs/sidebars.json
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/tags.md
Labels: pr: new feature
