Repository midwayjs/midway, pull requests merged in 2023-09, with the labels that each got.

#3219 docs: for faas change
  site/blog/2023-08-14-release-3.12.md
  site/docs/env_config.md
  site/docs/esm.md
  site/docs/extensions/bull.md
  site/docs/quick_guide.md
  site/docs/quickstart.md
  site/docs/sidebars.json
  site/i18n/en/docusaurus-plugin-content-docs/current/env_config.md
  site/i18n/en/docusaurus-plugin-content-docs/current/esm.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/bull.md
  site/i18n/en/docusaurus-plugin-content-docs/current/quick_guide.md
  site/i18n/en/docusaurus-plugin-content-docs/current/quickstart.md
  site/i18n/en/docusaurus-theme-classic/navbar.json
  site/lib/navbar.js
Labels: pr: documentation

#3236 fix(deps): update dependency @midwayjs/event-bus to v1.9.4
  packages/bootstrap/package.json
  packages/bootstrap/src/manager/base.ts
Labels: pr: dependencies

#3237 fix: remove querystring module
  packages-serverless/serverless-http-parser/package.json
Labels: pr: dependencies

#3267 chore: add suffix for package.json export
  packages-legacy/orm/package.json
  packages-legacy/runtime-engine/package.json
  packages-legacy/runtime-mock/package.json
  packages-legacy/serverless-app/package.json
  packages-legacy/serverless-aws-starter/package.json
  packages-legacy/serverless-fc-starter/package.json
  packages-legacy/serverless-fc-trigger/package.json
  packages-legacy/serverless-scf-starter/package.json
  packages-legacy/serverless-scf-trigger/package.json
  packages-legacy/serverless-vercel-starter/package.json
  packages-legacy/serverless-vercel-trigger/package.json
  packages-legacy/serverless-worker-starter/package.json
  packages-serverless/midway-fc-starter/package.json
  packages-serverless/serverless-http-parser/package.json
  packages/async-hooks-context-manager/package.json
  packages/axios/package.json
  packages/bootstrap/package.json
  packages/casbin-redis-adapter/package.json
  packages/casbin-typeorm-adapter/package.json
  packages/casbin/package.json
  packages/consul/package.json
  packages/core/package.json
  packages/cos/package.json
  packages/decorator/package.json
  packages/etcd/package.json
  packages/express-session/package.json
  packages/faas/package.json
  packages/grpc/package.json
  packages/i18n/package.json
  packages/info/package.json
  packages/kafka/package.json
  packages/mikro/package.json
  packages/mock/package.json
  packages/oss/package.json
  packages/otel/package.json
  packages/rabbitmq/package.json
  packages/redis/package.json
  packages/sequelize/package.json
  packages/session/package.json
  packages/socketio/package.json
  packages/static-file/package.json
  packages/swagger/package.json
  packages/tablestore/package.json
  packages/typeorm/package.json
  packages/web-express/package.json
  packages/web-koa/package.json
  packages/web/package.json
  packages/ws/package.json
Labels: pr: internal

#3297 docs(site): update passport.md
  site/docs/extensions/passport.md
Labels: pr: documentation
