Repository midwayjs/midway, pull requests merged in 2023-12, with the labels that each got.

#3474 fix: remove logger v3 compatible
  packages/bull/src/config/config.default.ts
  packages/cron/src/configuration.ts
  packages/typeorm/src/configuration.ts
  packages/web/src/config/config.default.ts
  packages/web/src/logger.ts
  packages/web/test/feature.test.ts
  packages/web/test/fixtures/feature/base-app-logger-v3/package.json
  packages/web/test/fixtures/feature/base-app-logger-v3/src/config/config.default.ts
  packages/web/test/fixtures/feature/base-app-logger-v3/src/config/config.unittest.ts
  packages/web/test/fixtures/feature/base-app-logger-v3/src/configuration.ts
Labels: pr: bug fix

#3478 feat: export http client options typings
  packages/core/src/util/httpclient.ts
Labels: pr: polish

#3490 docs: update validate.md
  site/docs/extensions/validate.md
Labels: pr: documentation

#3499 fix: add regenerate method for session security
  packages/session/src/interface.ts
  packages/session/src/lib/context.ts
  packages/session/src/lib/session.ts
  packages/session/test/fixtures/change-session-key/src/configuration.ts
  packages/session/test/index.test.ts
Labels: pr: bug fix

#3512 fix: serverless catch error when throw error
  packages/mock/src/creator.ts
Labels: pr: bug fix

#3507 fix: wrong agent logger
  packages/web/src/utils.ts
Labels: pr: bug fix

#3519 fix: support custom args pass through
  packages/mock/app.js
  packages/mock/function.js
  packages/mock/src/index.ts
  packages/mock/src/utils.ts
Labels: pr: bug fix

#3521 fix: wrong protocol get in local
  packages-serverless/serverless-http-parser/src/request.ts
  packages/mock/src/utils.ts
  packages/mock/test/util.test.ts
Labels: pr: bug fix

#3509 feat: inject ctx and app to leoric models
  packages/leoric/package.json
  packages/leoric/src/configuration.ts
  packages/leoric/test/fixtures/logger/package.json
  packages/leoric/test/fixtures/logger/src/config/config.default.ts
  packages/leoric/test/fixtures/logger/src/configuration.ts
  packages/leoric/test/fixtures/logger/src/controller/user.ts
  packages/leoric/test/fixtures/logger/src/model/post.ts
  packages/leoric/test/fixtures/logger/src/model/user.ts
  packages/leoric/test/fixtures/logger/src/service/user.ts
  packages/leoric/test/index.test.ts
  packages/leoric/test/logger.test.ts
Labels: pr: polish

#3473 feat: add redis health check
  packages/core/src/common/serviceFactory.ts
  packages/redis/src/configuration.ts
  packages/redis/src/manager.ts
Labels: pr: polish

#3526 feat: support client priority
  packages/core/src/common/serviceFactory.ts
  packages/core/src/interface.ts
  packages/core/test/common/serviceFactory.test.ts
  packages/redis/src/configuration.ts
  packages/redis/src/index.ts
  packages/redis/src/manager.ts
  packages/redis/test/index.test.ts
Labels: pr: new feature

#3492 feat: new cache manager component
  packages-legacy/cache/CHANGELOG.md
  packages-legacy/cache/README.md
  packages-legacy/cache/index.d.ts
  packages-legacy/cache/jest.config.js
  packages-legacy/cache/jest.setup.js
  packages-legacy/cache/package.json
  packages-legacy/cache/src/config/config.default.ts
  packages-legacy/cache/src/configuration.ts
  packages-legacy/cache/src/decorator/cacheKey.ts
  packages-legacy/cache/src/index.ts
  packages-legacy/cache/src/service/cache.ts
  packages-legacy/cache/test/cache.test.ts
  packages-legacy/cache/test/fixtures/cache-manager/package.json
  packages-legacy/cache/test/fixtures/cache-manager/src/configuration.ts
  packages-legacy/cache/test/fixtures/cache-manager/src/service/user.service.ts
  packages-legacy/cache/tsconfig.json
  packages-legacy/cache/typedoc.json
  packages/cache-manager-redis/README.md
  packages/cache-manager-redis/jest.config.js
  packages/cache-manager-redis/jest.setup.js
  packages/cache-manager-redis/package.json
  packages/cache-manager-redis/src/index.ts
  packages/cache-manager-redis/src/store.ts
  packages/cache-manager-redis/test/index.test.ts
  packages/cache-manager-redis/tsconfig.json
  packages/cache-manager-redis/typedoc.json
  packages/cache-manager/CHANGELOG.md
  packages/cache-manager/README.md
  packages/cache-manager/index.d.ts
  packages/cache-manager/jest.config.js
  packages/cache-manager/jest.setup.js
  packages/cache-manager/package.json
  packages/cache-manager/src/configuration.ts
  packages/cache-manager/src/decorator/cacheKey.ts
  packages/cache-manager/src/factory.ts
  packages/cache-manager/src/index.ts
  packages/cache-manager/src/interface.ts
  packages/cache-manager/test/factory.test.ts
  packages/cache-manager/test/fixtures/cache-decorator/package.json
  packages/cache-manager/test/fixtures/cache-decorator/src/configuration.ts
  packages/cache-manager/test/fixtures/cache-decorator/src/service/user.service.ts
  packages/cache-manager/test/fixtures/cache-manager/package.json
  packages/cache-manager/test/fixtures/cache-manager/src/configuration.ts
  packages/cache-manager/test/fixtures/cache-manager/src/service/user.service.ts
  packages/cache-manager/test/index.test.ts
  packages/cache-manager/tsconfig.json
  packages/cache-manager/typedoc.json
  packages/redis/index.d.ts
  packages/redis/src/index.ts
Labels: pr: new feature

#3528 feat: visit swagger json without include ui-dist & support custom ui
  packages/core/src/error/framework.ts
  packages/swagger/index.html
  packages/swagger/package.json
  packages/swagger/src/config/config.default.ts
  packages/swagger/src/index.ts
  packages/swagger/src/interfaces/index.ts
  packages/swagger/src/swaggerMiddleware.ts
  packages/swagger/src/ui/render.ts
  packages/swagger/test/fixtures/cats/src/configuration.ts
  packages/swagger/test/index.test.ts
Labels: pr: polish
