Repository midwayjs/midway, pull requests merged in 2023-06, with the labels that each got.

#3024 docs: update quick_guide.md
  site/docs/quick_guide.md
  site/i18n/en/docusaurus-plugin-content-docs/current/quick_guide.md
Labels: pr: documentation

#3025 fix: listener init data typings
  packages/core/src/common/dataListener.ts
Labels: pr: bug fix

#3021 feat(code-dye): outputType-html support show not end async call
  packages/code-dye/src/html.ts
  packages/code-dye/src/middleware.ts
  packages/code-dye/test/fixtures/koa/src/index.ts
  packages/code-dye/test/koa.test.ts
Labels: pr: polish

#3034 docs: change cron logger default fileLogName
  site/docs/extensions/cron.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/cron.md
Labels: pr: documentation

#3051 docs: update quickstart.md
  site/docs/quickstart.md
  site/i18n/en/docusaurus-plugin-content-docs/current/quickstart.md
Labels: pr: documentation
