Repository midwayjs/midway, pull requests merged in 2023-01, with the labels that each got.

#2629 fix: use ctx.traceId with otel
  packages/web-express/src/config/config.default.ts
  packages/web-koa/src/config/config.default.ts
  packages/web/src/config/config.default.ts
Labels: pr: bug fix

#2643 fix: output error when running test in jest environment
  packages/mock/src/creator.ts
Labels: pr: polish

#2640 fix: swagger one of with type
  packages/swagger/src/interfaces/index.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/parser.test.ts
  packages/validate/test/check.test.ts
Labels: pr: bug fix

#2654 feat: add @Singleton and get namespace api
  packages/core/src/baseFramework.ts
  packages/core/src/decorator/common/objectDef.ts
  packages/core/src/interface.ts
  packages/core/src/service/frameworkService.ts
  packages/core/test/baseFramework.test.ts
  packages/core/test/decorator/annotation/objectDef.test.ts
  packages/core/test/fixtures/base-app-multi-framework-shared/src/framework.ts
Labels: pr: new feature

#2626 fix: run stop lifecycle with reverse
  packages/core/src/service/lifeCycleService.ts
  packages/core/test/feature.test.ts
  packages/core/test/fixtures/base-app-configuration-stop-reverse/package.json
  packages/core/test/fixtures/base-app-configuration-stop-reverse/src/a/configuration.ts
  packages/core/test/fixtures/base-app-configuration-stop-reverse/src/b/configuration.ts
  packages/core/test/fixtures/base-app-configuration-stop-reverse/src/configuration.ts
Labels: pr: bug fix

#2589 chore: update output for lifecycle output
  packages/core/src/service/lifeCycleService.ts
Labels: pr: internal

#2606 feat: add ssr and custom trigger
  packages-serverless/midway-fc-starter/src/index.ts
  packages-serverless/serverless-http-parser/src/request.ts
  packages/core/src/decorator/faas/serverlessTrigger.ts
  packages/core/src/decorator/interface.ts
  packages/core/test/decorator/faas/__snapshots__/fun.test.ts.snap
  packages/core/test/decorator/faas/fun.test.ts
  packages/faas/src/decorator.ts
  packages/faas/src/framework.ts
  packages/faas/src/index.ts
  packages/faas/src/interface.ts
  packages/faas/src/starter.ts
  packages/faas/test/fixtures/base-app-event-decorator/package.json
  packages/faas/test/fixtures/base-app-event-decorator/src/configuration.ts
  packages/faas/test/fixtures/base-app-event-decorator/src/func.ts
  packages/faas/test/fixtures/base-app-event-decorator/src/index.ts
  packages/faas/test/new.test.ts
  packages/faas/test/starter.test.ts
  packages/mock/package.json
  packages/mock/src/creator.ts
  packages/mock/src/utils.ts
Labels: pr: polish

#2672 feat: add custom response args
  packages/faas/src/framework.ts
  packages/faas/src/interface.ts
  packages/faas/test/fixtures/base-app-custom-response/package.json
  packages/faas/test/fixtures/base-app-custom-response/src/configuration.ts
  packages/faas/test/fixtures/base-app-custom-response/src/func.ts
  packages/faas/test/fixtures/base-app-custom-response/src/index.ts
  packages/faas/test/new.test.ts
  packages/mock/src/creator.ts
Labels: pr: new feature

#2646 chore: change level for default logger level
  packages/core/src/config/config.default.ts
Labels: pr: polish

#2679 feat: support app enable ssl in dev mode
  packages/kafka/test/utils.ts
  packages/mock/src/creator.ts
  packages/mock/src/interface.ts
  packages/mock/src/utils.ts
Labels: pr: new feature

#2591 feat: add typeorm logger and logger lazy create
  packages/core/src/interface.ts
  packages/core/src/service/loggerService.ts
  packages/core/test/service/loggerService.test.ts
  packages/core/test/util.ts
  packages/typeorm/src/configuration.ts
  packages/typeorm/src/dataSourceManager.ts
  packages/typeorm/src/logger.ts
Labels: pr: new feature

#2687 feat: add simulator
  packages/core/src/baseFramework.ts
  packages/core/src/decorator/common/mock.ts
  packages/core/src/decorator/constant.ts
  packages/core/src/decorator/index.ts
  packages/core/src/interface.ts
  packages/core/src/service/lifeCycleService.ts
  packages/core/src/service/mockService.ts
  packages/core/src/setup.ts
  packages/core/test/common/applicationManager.test.ts
  packages/core/test/decorator/common/mock.test.ts
Labels: pr: new feature

#2688 fix(deps): update dependency consul to v1
  package.json
  packages/consul/package.json
  packages/consul/src/configuration.ts
  packages/consul/src/lib/provider.ts
  packages/core/src/service/slsFunctionService.ts
Labels: pr: breaking change, pr: dependencies

#2563 fix: remove content-length when proxy stream
  packages/http-proxy/src/middleware.ts
  packages/http-proxy/test/fixtures/koa/src/configuration.ts
  packages/http-proxy/test/koa.test.ts
  packages/upload/src/interface.ts
Labels: pr: bug fix

#2690 fix: create default logger when typeorm logger set undefined
  packages/typeorm/src/dataSourceManager.ts
Labels: pr: bug fix

#2693 chore(core): add type DecoratorMetaData for custom decorator
  packages/core/src/interface.ts
  packages/core/src/service/decoratorService.ts
Labels: pr: maintenance

#2694 fix: missing pipes args in web param
  packages/core/src/decorator/web/paramMapping.ts
  packages/core/src/interface.ts
  packages/core/src/service/decoratorService.ts
  packages/core/test/decorator/web/__snapshots__/paramMapping.test.ts.snap
  packages/core/test/decorator/web/paramMapping.test.ts
  packages/mock/src/creator.ts
Labels: pr: bug fix

#2695 fix: web param set wrong pipe position
  packages/core/src/decorator/web/paramMapping.ts
  packages/core/test/decorator/web/__snapshots__/paramMapping.test.ts.snap
  packages/decorator/test/web/__snapshots__/paramMapping.test.ts.snap
  packages/validate/src/configuration.ts
  packages/validate/src/decorator/valid.ts
  packages/validate/src/pipe.ts
  packages/validate/test/check.test.ts
Labels: pr: bug fix
