Repository midwayjs/midway, pull requests merged in 2023-05, with the labels that each got.

#2964 fix: model get different repository by type
  packages/typeorm/src/configuration.ts
Labels: pr: bug fix

#2986 docs: fix validate.md defaultValuePipe variable name error
  site/docs/extensions/validate.md
Labels: pr: documentation

#2996 feat: support new faas v3 entry
  packages/faas/src/starter.ts
  packages/mock/src/creator.ts
  packages/mock/src/interface.ts
  packages/mock/test/fixtures/base-faas-without-yaml/index.js
  packages/mock/test/fixtures/base-faas-without-yaml/package.json
  packages/mock/test/fixtures/base-faas-without-yaml/src/configuration.ts
  packages/mock/test/fixtures/base-faas-without-yaml/src/event.ts
  packages/mock/test/fixtures/base-faas-without-yaml/tsconfig.json
  packages/mock/test/new.test.ts
Labels: pr: polish

#3000 fix: bootstrap close entry
  packages/mock/src/creator.ts
  packages/mock/src/interface.ts
Labels: pr: bug fix
