Repository midwayjs/midway, pull requests merged in 2024-01, with the labels that each got.

#3533 fix(redis): Check the status of the redis client before closing redis
  packages/redis/src/manager.ts
Labels: pr: bug fix

#3544 feat(serverless-worker-starter): support noslate event
  packages-legacy/serverless-worker-starter/src/interface.ts
  packages-legacy/serverless-worker-starter/src/runtime.ts
Labels: pr: polish

#3549 feat: upgrade mikro to v6
  packages/mikro/package.json
  packages/mikro/src/configuration.ts
  packages/mikro/src/dataSourceManager.ts
  packages/mikro/src/interface.ts
  packages/mikro/test/fixtures/base-fn-origin/sqlite-schema.sql
  packages/mikro/test/fixtures/base-fn-origin/src/config/config.default.ts
  site/docs/extensions/mikro.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/mikro.md
Labels: pr: dependencies, pr: new feature

#3555 fix: Swagger tags are duplicate, deprecated field in ApiOperation is …
  packages/swagger/src/documentBuilder.ts
  packages/swagger/src/index.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/parser.test.ts
Labels: pr: bug fix

#3547 docs: add swagger doc
  packages/cache-manager/src/configuration.ts
  packages/cache-manager/src/decorator/cacheKey.ts
  packages/cache-manager/src/index.ts
  packages/cache-manager/test/fixtures/cache-decorator/src/service/user.service.ts
  packages/cache-manager/test/index.test.ts
  packages/core/src/error/framework.ts
  packages/swagger/src/config/config.default.ts
  packages/swagger/src/ui/render.ts
  packages/swagger/test/index.test.ts
  site/blog/2024-01-13-release-3.14.md
  site/docs/extensions/caching.md
  site/docs/extensions/static_file.md
  site/docs/extensions/swagger.md
  site/docs/extensions/upload.md
  site/docs/service_factory.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/caching.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/static_file.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/swagger.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/upload.md
  site/i18n/en/docusaurus-plugin-content-docs/current/service_factory.md
Labels: pr: documentation

#2741 fix: normal return will be close stream
  packages-serverless/serverless-http-parser/src/application.ts
  packages-serverless/serverless-http-parser/src/http/res.ts
  packages-serverless/serverless-http-parser/test/index.test.ts
Labels: pr: bug fix

#3559 fix: swagger-ui-dist require missing
  packages/swagger/src/config/config.default.ts
Labels: pr: bug fix

#3560 fix: swagger render json not match path
  packages/swagger/src/ui/render.ts
  site/blog/2024-01-13-release-3.14.md
  site/docs/extensions/caching.md
  site/docs/service_factory.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/caching.md
  site/i18n/en/docusaurus-plugin-content-docs/current/service_factory.md
Labels: pr: bug fix

#3573 fix: lifecycle inject fail in configuration
  packages/core/src/service/healthService.ts
  packages/core/src/service/lifeCycleService.ts
Labels: pr: bug fix

#3574 fix: entityManager chaos under multiple instances
  packages/mikro/package.json
  packages/mikro/src/configuration.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/config/config.default.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/configuration.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/controller/m1.controller.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/entity/author.entity.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/entity/user.entity.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/index.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/service/book.service.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/config/config.default.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/config/config.unittest.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/configuration.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/controller/home.controller.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/entity/book.entity.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/interface.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/mikro-orm.config.ts
  packages/mikro/test/index.test.ts
Labels: pr: bug fix

#3578 fix(swagger): swagger-UI not show exception after fixing global configuration
  packages/swagger/src/configuration.ts
  packages/swagger/src/documentBuilder.ts
  packages/swagger/src/swaggerExplorer.ts
Labels: pr: bug fix

#3579 fix: app throw initialize error when invoke close method
  packages/mock/app.js
  packages/mock/function.js
Labels: pr: bug fix

#3583 fix(swagger): Updated test cases to fix duplicate interface addresses…
  packages/swagger/src/documentBuilder.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/index.test.ts
Labels: pr: bug fix

#3588 docs: update egg.md
  site/docs/extensions/egg.md
Labels: pr: documentation

#3602 ci: add nodejs LTS
  .github/workflows/nodejs.yml
Labels: pr: internal

#3601 feat: custom Ignore swagger endpoint
  packages/swagger/src/decorators/api-exclude-controller.decorator.ts
  packages/swagger/src/interfaces/index.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/src/swaggerMiddleware.ts
  packages/swagger/test/parser.test.ts
  packages/ws/package.json
  site/docs/extensions/swagger.md
  site/docs/extensions/ws.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/egg.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/swagger.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/ws.md
Labels: pr: polish

#3605 docs: update http-proxy.md
  site/docs/extensions/http-proxy.md
Labels: pr: documentation
