Repository midwayjs/midway, pull requests merged in 2024-03, with the labels that each got.

#3682 docs: pdate awesome_midway.md
  site/docs/awesome_midway.md
Labels: pr: documentation

#3680 chore: use Axios for interface export
  packages/axios/src/index.ts
  packages/axios/src/interface.ts
Labels: pr: polish

#3704 fix(mikro): RequestContext middleware
  packages/mikro/src/configuration.ts
  packages/mikro/src/index.ts
  packages/mikro/src/mikro.middleware.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/config/config.default.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/mikro-orm.config.ts
Labels: pr: bug fix

#3707 fix: bullLogger with undefined value when emit error
  packages/bull/src/framework.ts
  packages/bull/test/index.test.ts
Labels: pr: bug fix

#3708 chore: update request content middleware and use default source name …
  packages/mikro/src/configuration.ts
  packages/mikro/src/dataSourceManager.ts
  packages/mikro/src/index.ts
  packages/mikro/src/mikro.middleware.ts
Labels: pr: polish

#3709 fix(mikro): Ensure dataSourceName/contextName used in InjectRepository
  packages/mikro/src/configuration.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/config/config.default.ts
  packages/mikro/test/fixtures/multi-enitymanager/src/components/m1/src/controller/m1.controller.ts
  packages/mikro/test/index.test.ts
Labels: pr: bug fix

#3714 the dosc fix of extension casbin
  site/docs/extensions/casbin.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/casbin.md
Labels: pr: documentation

#3715 fix: cache manager cache key overwrite when use custom logic
  packages/cache-manager/src/configuration.ts
  packages/cache-manager/test/fixtures/cache-decorator/src/service/user.service.ts
  packages/cache-manager/test/index.test.ts
Labels: pr: bug fix

#3722 fix: enable console transport in serverless env
  packages/faas/src/config.default.ts
Labels: pr: bug fix

#3734 fix(upload):parameter "whitelist" supports the function type
  packages/upload/src/interface.ts
  packages/upload/src/middleware.ts
Labels: pr: bug fix
