Repository midwayjs/midway, pull requests merged in 2024-07, with the labels that each got.

#3929 docs: update awesome_midway.md
  site/docs/awesome_midway.md
Labels: pr: documentation

#3971 feat: add allowFieldsDuplication options
  packages/upload/src/config/config.default.ts
  packages/upload/src/interface.ts
  packages/upload/src/middleware.ts
  packages/upload/src/parse.ts
  packages/upload/test/fixtures/koa-function-duplicate-fields/src/configuration.ts
  packages/upload/test/koa.test.ts
Labels: pr: polish

#3981 fix: single field when allowFieldsDuplication enabled
  packages/upload/src/parse.ts
  packages/upload/test/koa.test.ts
Labels: pr: bug fix
