Repository midwayjs/midway, pull requests merged in 2024-04, with the labels that each got.

#3741 feat: support upload mime type white list using function type
  packages/upload/src/interface.ts
  packages/upload/src/middleware.ts
  packages/upload/test/fixtures/koa-function-whitelist/src/configuration.ts
  packages/upload/test/koa.test.ts
Labels: pr: polish

#3764 fix: socket with regexp namespace
  packages/socketio/src/framework.ts
  packages/socketio/test/fixtures/base-app-namespace-regexp/package.json
  packages/socketio/test/fixtures/base-app-namespace-regexp/src/configuration.ts
  packages/socketio/test/fixtures/base-app-namespace-regexp/src/service/user.ts
  packages/socketio/test/fixtures/base-app-namespace-regexp/src/socket/api.ts
  packages/socketio/test/index.test.ts
Labels: pr: bug fix

#3786 fix: remove typings from the cron module since it includes its own types
  packages/cron/package.json
Labels: pr: bug fix

#3788 fix(docs): typo
  site/docs/container.md
Labels: pr: documentation

#3791 feat(bull-board): save the result of createBullBoard
  packages/bull-board/src/board.middleware.ts
Labels: pr: polish

#3797 feat Support http server opts
  packages/web-express/src/framework.ts
  packages/web-express/src/interface.ts
  packages/web-koa/src/framework.ts
  packages/web-koa/src/interface.ts
  packages/web/src/framework/web.ts
  packages/web/src/interface.ts
Labels: pr: polish

#3798 refactor: add the bullBoardManager class along with documentation
  packages/bull-board/src/board.manager.ts
  packages/bull-board/src/board.middleware.ts
  packages/bull-board/src/index.ts
  packages/bull-board/test/index.test.ts
  site/docs/extensions/bull.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/bull.md
Labels: pr: polish

#3807 fix: certificate error in web scene
  packages/express-session/README.md
  packages/express-session/src/store.ts
  packages/express-session/test/index.test.ts
  packages/web-express/src/framework.ts
  packages/web-koa/src/framework.ts
  packages/web/src/framework/web.ts
Labels: pr: bug fix
