Repository midwayjs/midway, pull requests merged in 2024-12, with the labels that each got.

#4221 feat: Add ignoreKey configuration, support setting key to hide the entire line of info information
  packages/info/src/config.default.ts
  packages/info/src/infoService.ts
  packages/info/src/interface.ts
  packages/info/test/__snapshots__/index.test.ts.snap
  packages/info/test/index.test.ts
Labels: pr: polish

#4220 refactor: add InfoType enumeration to supplement the missing ts syntax type
  packages/info/src/infoService.ts
  packages/info/src/interface.ts
  packages/info/src/middleware/info.middleware.ts
  packages/info/src/utils.ts
Labels: pr: polish

#4232 docs: use https for github domains
  README.en-US.md
  README.md
  package.json
  packages-legacy/cache/README.md
  packages/async-hooks-context-manager/README.md
  packages/axios/README.md
  packages/bootstrap/README.md
  packages/bull-board/README.md
  packages/bull/README.md
  packages/busboy/README.md
  packages/cache-manager/README.md
  packages/captcha/README.md
  packages/casbin-redis-adapter/README.md
  packages/casbin-typeorm-adapter/README.md
  packages/casbin/README.md
  packages/code-dye/README.md
  packages/consul/README.md
  packages/core/README.md
  packages/cos/README.md
  packages/cron/README.md
  packages/decorator/README.md
  packages/etcd/README.md
  packages/grpc/README.md
  packages/i18n/README.md
  packages/info/README.md
  packages/kafka/README.md
  packages/leoric/README.md
  packages/mikro/README.md
  packages/mock/README.md
  packages/mongoose/README.md
  packages/mqtt/README.md
  packages/oss/README.md
  packages/otel/README.md
  packages/rabbitmq/README.md
  packages/redis/README.md
  packages/sequelize/README.md
  packages/socketio/README.md
  packages/static-file/README.md
  packages/swagger/README.md
  packages/tablestore/README.md
  packages/tags/README.md
  packages/tenant/README.md
  packages/validate/README.md
  packages/view-ejs/README.md
  packages/view-nunjucks/README.md
  packages/view/README.md
  packages/web-express/README.md
  packages/web-koa/README.md
  packages/web/README.md
  packages/ws/README.md
Labels: pr: documentation

#4236 feat: Unification framework logger
  packages/bull/src/config/config.default.ts
  packages/bull/src/framework.ts
  packages/core/src/baseFramework.ts
  packages/core/src/interface.ts
  packages/core/src/setup.ts
  packages/core/test/baseFramework.test.ts
  packages/core/test/fixtures/base-app-custom-framework-logger/src/framework.ts
  packages/cron/src/configuration.ts
  packages/cron/src/framework.ts
  packages/grpc/src/configuration.ts
  packages/grpc/src/provider/framework.ts
  packages/kafka/src/configuration.ts
  packages/kafka/src/framework.ts
  packages/kafka/src/kafka.ts
  packages/kafka/test/index.test.ts
  packages/mqtt/src/configuration.ts
  packages/mqtt/src/framework.ts
  packages/socketio/test/index.test.ts
  packages/web-express/src/config/config.default.ts
  packages/web-koa/src/config/config.default.ts
  packages/web/src/config/config.default.ts
  packages/web/src/framework/web.ts
  packages/web/test/feature.test.ts
  packages/web/test/fixtures/feature/base-app-set-ctx-logger/src/config/config.default.ts
  packages/ws/src/configuration.ts
  packages/ws/src/framework.ts
  pnpm-lock.yaml
Labels: pr: breaking change, pr: new feature

#4242 fix: use security svg-captcha and add more options
  packages/captcha/package.json
  packages/captcha/src/interface.ts
  packages/captcha/src/service.ts
  site/docs/extensions/captcha.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/captcha.md
Labels: pr: bug fix

#4250 feat: add lifecycle timeout options
  packages/core/src/config/config.default.ts
  packages/core/src/error/framework.ts
  packages/core/src/functional/configuration.ts
  packages/core/src/interface.ts
  packages/core/src/service/healthService.ts
  packages/core/src/service/lifeCycleService.ts
  packages/core/src/util/index.ts
  packages/core/src/util/timeout.ts
  packages/core/test/service/lifeCycleService.test.ts
  packages/core/test/util/timeout.test.ts
  packages/core/test/util/util.test.ts
Labels: pr: new feature
