Repository midwayjs/midway, pull requests merged in 2024-06, with the labels that each got.

#3886 fix(swagger): miss dto required from schema
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/parser.test.ts
Labels: pr: bug fix

#3889 fix: get origin value from redis store
  packages/cache-manager/src/store.ts
  packages/cache-manager/test/store.test.ts
Labels: pr: bug fix

#3899 docs(site): update awesome_midway.md
  site/docs/awesome_midway.md
  site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
Labels: pr: documentation

#3927 fix: main ci
  packages/core/test/logger.test.ts
  packages/core/test/util.ts
Labels: pr: internal
