Repository midwayjs/midway, pull requests merged in 2024-10, with the labels that each got.

#4120 refactor: remove pipeline code
  packages/core/src/context/requestContainer.ts
  packages/core/src/decorator/common/pipeline.ts
  packages/core/src/decorator/constant.ts
  packages/core/src/decorator/index.ts
  packages/core/src/index.ts
  packages/core/src/service/frameworkService.ts
  packages/core/src/service/pipelineService.ts
  packages/core/test/decorator/common/__snapshots__/pipeline.test.ts.snap
  packages/core/test/decorator/common/pipeline.test.ts
  packages/core/test/features/pipeline.test.ts
  packages/core/test/fixtures/pipeline.ts
  packages/web/src/utils.ts
  packages/web/test/enhance.test.ts
  packages/web/test/fixtures/enhance/base-app-decorator/src/lib/service.ts
  packages/web/test/fixtures/enhance/base-app-decorator/src/lib/stages.ts
Labels: pr: breaking change

#4124 docs: update awesome_midway.md
  site/docs/awesome_midway.md
Labels: pr: documentation

#4127 docs: update awesome_midway.md
  site/docs/awesome_midway.md
Labels: pr: documentation

#4131 docs(awesome_midway.md): add @mwcp/paradedb
  site/docs/awesome_midway.md
  site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
Labels: pr: documentation

#4121 feat: support circular ref & lazy inject & constructor inject
  .github/workflows/nodejs.yml
  .run/All Tests in egg.run.xml
  packages/bootstrap/src/bootstrap.ts
  packages/core/src/baseFramework.ts
  packages/core/src/constants.ts
  packages/core/src/context/container.ts
  packages/core/src/context/managedResolverFactory.ts
  packages/core/src/context/requestContainer.ts
  packages/core/src/decorator/common/inject.ts
  packages/core/src/decorator/constant.ts
  packages/core/src/decorator/decoratorManager.ts
  packages/core/src/decorator/index.ts
  packages/core/src/decorator/metadataManager.ts
  packages/core/src/definitions/functionDefinition.ts
  packages/core/src/definitions/objectCreator.ts
  packages/core/src/definitions/objectDefinition.ts
  packages/core/src/definitions/properties.ts
  packages/core/src/error/framework.ts
  packages/core/src/interface.ts
  packages/core/src/legacy/decorator.ts
  packages/core/src/service/decoratorService.ts
  packages/core/src/service/frameworkService.ts
  packages/core/src/setup.ts
  packages/core/src/util/contextUtil.ts
  packages/core/test/common/notFoundError.test.ts
  packages/core/test/context/applicationContext.test.ts
  packages/core/test/context/container.test.ts
  packages/core/test/context/managedResolverFactory.test.ts
  packages/core/test/context/midwayContainer.test.ts
  packages/core/test/context/requestContainer.test.ts
  packages/core/test/decorator/common/inject.test.ts
  packages/core/test/decorator/common/utils.test.ts
  packages/core/test/decorator/index.test.ts
  packages/core/test/definitions/functionDefinition.test.ts
  packages/core/test/definitions/objectCreator.test.ts
  packages/core/test/definitions/properties.test.ts
  packages/core/test/error/framework.test.ts
  packages/core/test/feature.test.ts
  packages/core/test/fixtures/app-with-component-inject-with-class/circular/src/b.ts
  packages/core/test/fixtures/circular_dependency.ts
  packages/core/test/fixtures/mix_sample.ts
  packages/core/test/issue.test.ts
  packages/core/test/legacy/decorator.test.ts
  packages/kafka/test/fixtures/base-app-multi-different-topic/src/comsumer/userConsumer.ts
  packages/kafka/test/index.test.ts
  packages/mqtt/scripts/mosquitto.conf
  packages/mqtt/scripts/start.sh
  packages/mqtt/test/fixtures/base-app/src/configuration.ts
  packages/mqtt/test/index.test.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/typeorm/src/configuration.ts
  packages/web/app/extend/context.js
  packages/web/test/fixtures/enhance/base-app-decorator/src/lib/circular.ts
Labels: pr: new feature

#4155 docs(awesome_midway.md): update @mwcp/otel
  site/docs/awesome_midway.md
  site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
Labels: pr: documentation
