Repository midwayjs/midway, pull requests merged in 2024-09, with the labels that each got.

#4046 fix(kafkajs): Fix the issue where the consumer method of the kafkajs component returns true to trigger a commit parameter error.
  packages/kafka/src/framework.ts
Labels: pr: bug fix

#4047 feat: add ctx for the static tpl of response
  packages/core/src/interface.ts
  packages/core/src/response/base.ts
  packages/core/src/response/http.ts
  packages/core/src/response/sse.ts
  packages/core/src/response/stream.ts
  packages/core/test/response/base.test.ts
  packages/core/test/response/http.test.ts
Labels: pr: polish

#4050 fix(swagger): miss dto description from schema
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/parser.test.ts
Labels: type: bug

#4062 fix: swagger api tag for router
  packages/swagger/src/config/config.default.ts
  packages/swagger/src/documentBuilder.ts
  packages/swagger/src/interfaces/index.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/parser.test.ts
Labels: pr: bug fix

#4075 fix: swagger body array type
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/parser.test.ts
Labels: pr: bug fix

#4061 fix: dataSourcePriority missing default value
  packages/core/src/common/dataSourceManager.ts
  packages/mongoose/src/configuration.ts
  packages/mongoose/test/index.test.ts
Labels: pr: bug fix

#4058 fix: http client will be override default options
  packages/core/src/util/httpclient.ts
  packages/core/test/util/httpclient.test.ts
Labels: pr: bug fix

#4074 feat: busboy support async generator mode
  .gitignore
  packages/busboy/src/error.ts
  packages/busboy/src/interface.ts
  packages/busboy/src/middleware.ts
  packages/busboy/src/utils.ts
  packages/busboy/test/clean.test.ts
  packages/busboy/test/express.test.ts
  packages/busboy/test/fixtures/koa-file/src/configuration.ts
  packages/busboy/test/fixtures/koa-stream/src/configuration.ts
  packages/busboy/test/index.test.ts
  packages/busboy/test/koa.test.ts
  packages/core/src/util/webRouterParam.ts
  site/blog/2024-08-29-release-3.17.md
  site/docs/extensions/busboy.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/busboy.md
Labels: pr: new feature

#4082 fix: showcase of ssl with mwtsc
  packages/mock/app.js
  packages/web-express/src/framework.ts
  packages/web-koa/src/framework.ts
  packages/web/src/framework/web.ts
Labels: pr: bug fix

#4083 fix: ensure compatibility with Swagger response schema and fix the parsing of enum types
  packages-legacy/cache/src/service/cache.ts
  packages/cache-manager/package.json
  packages/cache-manager/test/index.test.ts
  packages/swagger/src/common/enum.utils.ts
  packages/swagger/src/decorators/api-exclude-controller.decorator.ts
  packages/swagger/src/decorators/api-extra-model.decorator.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/parser.test.ts
  packages/swagger/test/util.test.ts
Labels: pr: bug fix

#4096 docs(awesome_midway.md): update @mwcp/pgmq
  site/docs/awesome_midway.md
Labels: pr: documentation
