Repository midwayjs/midway, pull requests merged in 2024-11, with the labels that each got.

#4130 chore(core): add comment of DataSourceManager.stop()
  packages/core/src/common/dataSourceManager.ts
Labels: pr: internal

#4176 fix: wrong object format for sse response
  packages/core/src/response/sse.ts
Labels: pr: bug fix

#4180 fix: static file path handling in pkg environment
  packages/core/src/service/environmentService.ts
  packages/core/test/service/environmentService.test.ts
  packages/static-file/src/middleware/static.middleware.ts
Labels: pr: bug fix

#4150 feat: add performance manager
  .eslintrc.json
  packages/core/src/common/performanceManager.ts
  packages/core/src/index.ts
  packages/core/src/service/frameworkService.ts
  packages/core/src/service/lifeCycleService.ts
  packages/core/src/setup.ts
  packages/core/test/common/performanceManager.test.ts
  packages/mock/app.js
  packages/mock/function.js
Labels: pr: polish

#4151 feat: add grouping for mock data
  packages/core/src/service/mockService.ts
  packages/core/test/service/mockService.test.ts
  packages/mock/src/mock.ts
  site/docs/built_in_service.md
  site/docs/mock.md
  site/i18n/en/docusaurus-plugin-content-docs/current/built_in_service.md
  site/i18n/en/docusaurus-plugin-content-docs/current/mock.md
Labels: pr: new feature

#4154 feat(kafka): refactor framework and add factory service for producer and admin
  packages/core/src/common/typedResourceManager.ts
  packages/core/src/index.ts
  packages/core/src/interface.ts
  packages/core/test/common/typedResourceManager.test.ts
  packages/kafka/index.d.ts
  packages/kafka/src/configuration.ts
  packages/kafka/src/decorator.ts
  packages/kafka/src/framework.ts
  packages/kafka/src/index.ts
  packages/kafka/src/interface.ts
  packages/kafka/src/manager.ts
  packages/kafka/src/service.ts
  packages/kafka/test/fixtures/base-app-auto-commit/src/configuration.ts
  packages/kafka/test/fixtures/base-app-manual-committing/src/configuration.ts
  packages/kafka/test/fixtures/base-app-multi-different-topic/src/configuration.ts
  packages/kafka/test/fixtures/base-app-multi-some-topic/src/configuration.ts
  packages/kafka/test/fixtures/base-app/src/configuration.ts
  packages/kafka/test/index.test.ts
  site/docs/extensions/kafka.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/kafka.md
Labels: pr: polish

#4192 fix(leoric): keep multiple datasources from conflicting base model
  packages/leoric/package.json
  packages/leoric/src/dataSourceManager.ts
  packages/leoric/test/fixtures/multi/package.json
  packages/leoric/test/fixtures/multi/src/config/config.default.ts
  packages/leoric/test/fixtures/multi/src/configuration.ts
  packages/leoric/test/fixtures/multi/src/model/user.ts
  packages/leoric/test/fixtures/multi/src/service/user.ts
  packages/leoric/test/fixtures/multi/src/subsystem/controller/post.ts
  packages/leoric/test/fixtures/multi/src/subsystem/model/post.ts
  packages/leoric/test/fixtures/multi/src/subsystem/service/post.ts
  packages/leoric/test/multi.test.ts
Labels: pr: bug fix
