Repository midwayjs/midway, pull requests merged in 2024-05, with the labels that each got.

#3700 fix: health check missing this resolver
  packages/core/src/service/healthService.ts
  packages/core/test/fixtures/app-with-health-check/src/configuration.ts
Labels: pr: bug fix

#3710 feat: add instance args for parameter decorator options
  packages/core/src/service/decoratorService.ts
Labels: pr: polish

#3756 refactor: Refactor swagger module
  .babelrc
  package.json
  packages/swagger/package.json
  packages/swagger/src/decorators/api-header.decorator.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/index.test.ts.snap
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/parser.test.ts
  packages/swagger/tsconfig.json
  site/docs/extensions/swagger.md
Labels: pr: bug fix

#3833 docs: update orm.md
  site/docs/extensions/orm.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/orm.md
Labels: pr: documentation

#3842 fix: make request.query writeable
  packages/web-koa/src/framework.ts
  packages/web-koa/test/index.test.ts
Labels: pr: bug fix

#3840 fix: export named error for tenant component
  packages/tenant/src/index.ts
  site/docs/extensions/tenant.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/tenant.md
Labels: pr: bug fix

#3848 docs: update tenant.md
  site/docs/extensions/tenant.md
Labels: pr: documentation

#3849 docs: update en version tenant.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/tenant.md
Labels: pr: documentation

#3854 docs: fix typo in mock.md
  site/docs/mock.md
Labels: pr: documentation

#3871 docs: update release schedule docs, mark v2 as EOL
  site/docs/release_schedule.md
Labels: pr: documentation
