Repository midwayjs/midway, pull requests merged in 2024-08, with the labels that each got.

#3993 fix: remove authenticate when create data source
  packages/sequelize/src/configuration.ts
  packages/sequelize/src/dataSourceManager.ts
  packages/sequelize/test/index.test.ts
Labels: pr: bug fix

#4007 docs: fix typo
  site/docs/extensions/validate.md
Labels: pr: documentation

#4008 docs: extensions koa typo
  site/docs/extensions/koa.md
Labels: pr: documentation

#4018 docs(awesome_midway): add @mwcp/pgmq
  site/docs/awesome_midway.md
  site/i18n/en/docusaurus-plugin-content-docs/current/awesome_midway.md
Labels: pr: documentation

#3875 refactor: upload component use busboy
  packages/busboy/README.md
  packages/busboy/index.d.ts
  packages/busboy/jest.config.js
  packages/busboy/jest.setup.js
  packages/busboy/package.json
  packages/busboy/src/configuration.ts
  packages/busboy/src/constants.ts
  packages/busboy/src/error.ts
  packages/busboy/src/index.ts
  packages/busboy/src/interface.ts
  packages/busboy/src/middleware.ts
  packages/busboy/src/parse.ts
  packages/busboy/src/utils.ts
  packages/busboy/test/clean.test.ts
  packages/busboy/test/express.test.ts
  packages/busboy/test/faas.test.ts
  packages/busboy/test/fixtures/1.from-jpg.png
  packages/busboy/test/fixtures/1.jpg
  packages/busboy/test/fixtures/1.more
  packages/busboy/test/fixtures/1.tar.gz
  packages/busboy/test/fixtures/1.test
  packages/busboy/test/fixtures/3kb.png
  packages/busboy/test/fixtures/clean/f.yml
  packages/busboy/test/fixtures/clean/src/configuration.ts
  packages/busboy/test/fixtures/err.jpg
  packages/busboy/test/fixtures/express-file/src/configuration.ts
  packages/busboy/test/fixtures/express-stream/src/configuration.ts
  packages/busboy/test/fixtures/faas/f.yml
  packages/busboy/test/fixtures/faas/src/configuration.ts
  packages/busboy/test/fixtures/koa-ext-null/src/configuration.ts
  packages/busboy/test/fixtures/koa-file-mime/src/configuration.ts
  packages/busboy/test/fixtures/koa-file/src/configuration.ts
  packages/busboy/test/fixtures/koa-function-whitelist/src/configuration.ts
  packages/busboy/test/fixtures/koa-stream/src/configuration.ts
  packages/busboy/test/fixtures/test.pdf
  packages/busboy/test/fixtures/web-file/package.json
  packages/busboy/test/fixtures/web-file/src/config/config.default.ts
  packages/busboy/test/fixtures/web-file/src/configuration.ts
  packages/busboy/test/fixtures/web-stream/package.json
  packages/busboy/test/fixtures/web-stream/src/config/config.default.ts
  packages/busboy/test/fixtures/web-stream/src/configuration.ts
  packages/busboy/test/index.test.ts
  packages/busboy/test/koa.test.ts
  packages/busboy/test/resource/default.txt
  packages/busboy/test/web.test.ts
  packages/busboy/tsconfig.json
  packages/busboy/typedoc.json
  packages/core/src/common/middlewareManager.ts
  packages/core/src/interface.ts
  packages/core/src/service/middlewareService.ts
  packages/core/test/common/__snapshots__/middlewareManager.test.ts.snap
  packages/core/test/common/middlewareManager.test.ts
  packages/core/test/service/middlewareService.test.ts
  site/docs/extensions/busboy.md
  site/docs/middleware.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/busboy.md
  site/i18n/en/docusaurus-plugin-content-docs/current/middleware.md
Labels: pr: new feature, pr: polish

#3982 feat: support response helper and sse util
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/interface.ts
  packages/core/src/response/base.ts
  packages/core/src/response/http.ts
  packages/core/src/response/index.ts
  packages/core/src/response/sse.ts
  packages/core/src/response/stream.ts
  packages/core/test/response/base.test.ts
  packages/core/test/response/http.test.ts
Labels: pr: new feature

#4013 fix(core): DataSourceManagerConfigOption generic OPTIONS now no changes by PowerPartial
  packages/core/src/interface.ts
Labels: pr: polish
