Repository midwayjs/midway, pull requests merged in 2024-02, with the labels that each got.

#3617 fix: isAuthenticated missing this
  packages/passport/index.d.ts
  packages/passport/src/passport/passport.service.ts
  packages/passport/test/fixtures/passport-express/src/test.controller.ts
  packages/passport/test/fixtures/passport-web/src/test.controller.ts
Labels: pr: bug fix

#3630 fix: ignore custom param decorator in swagger
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/parser.test.ts
Labels: pr: bug fix

#3648 fix: ctx get logger with custom logger
  packages/core/src/baseFramework.ts
  packages/core/src/common/loggerFactory.ts
  packages/core/test/baseFramework.test.ts
  packages/core/test/fixtures/base-app-custom-framework-logger/package.json
  packages/core/test/fixtures/base-app-custom-framework-logger/src/configuration.ts
  packages/core/test/fixtures/base-app-custom-framework-logger/src/framework.ts
  packages/core/test/util.ts
Labels: pr: bug fix

#3652 fix: missing swagger ui render options
  packages/swagger/src/interfaces/index.ts
  packages/swagger/src/ui/render.ts
Labels: pr: bug fix

#3655 feat: support custom param decorator throw error
  packages/core/src/decorator/web/paramMapping.ts
  packages/core/test/decorator/web/__snapshots__/paramMapping.test.ts.snap
Labels: pr: polish

#3658 feat: add mqtt module
  packages/core/src/baseFramework.ts
  packages/core/src/common/serviceFactory.ts
  packages/kafka/src/configuration.ts
  packages/kafka/src/framework.ts
  packages/kafka/src/index.ts
  packages/kafka/src/kafka.ts
  packages/mqtt/README.md
  packages/mqtt/index.d.ts
  packages/mqtt/jest.config.js
  packages/mqtt/jest.setup.js
  packages/mqtt/package.json
  packages/mqtt/src/configuration.ts
  packages/mqtt/src/decorator.ts
  packages/mqtt/src/framework.ts
  packages/mqtt/src/index.ts
  packages/mqtt/src/interface.ts
  packages/mqtt/src/service.ts
  packages/mqtt/test/fixtures/base-app-no-pub-sub/package.json
  packages/mqtt/test/fixtures/base-app-no-pub-sub/src/configuration.ts
  packages/mqtt/test/fixtures/base-app/package.json
  packages/mqtt/test/fixtures/base-app/src/comsumer/userConsumer.ts
  packages/mqtt/test/fixtures/base-app/src/configuration.ts
  packages/mqtt/test/index.test.ts
  packages/mqtt/tsconfig.json
  packages/mqtt/typedoc.json
  packages/rabbitmq/src/configuration.ts
Labels: pr: new feature

#3659 feat: add ApiExcludeSecurity decorator
  packages/swagger/src/constants.ts
  packages/swagger/src/decorators/api-exclude-endpoint.decorator.ts
  packages/swagger/src/decorators/api-header.decorator.ts
  packages/swagger/src/decorators/api-operation.decorator.ts
  packages/swagger/src/decorators/api-response.decorator.ts
  packages/swagger/src/decorators/api-security.decorator.ts
  packages/swagger/src/decorators/helpers.ts
  packages/swagger/src/interfaces/index.ts
  packages/swagger/src/swaggerExplorer.ts
  packages/swagger/test/__snapshots__/parser.test.ts.snap
  packages/swagger/test/parser.test.ts
  site/docs/extensions/swagger.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/swagger.md
Labels: pr: new feature

#3669 fix: passport missing ctx.setHeader
  packages/passport/package.json
  packages/passport/src/passport/passport.service.ts
  packages/passport/test/fixtures/passport-koa-bearer-fail/package.json
  packages/passport/test/fixtures/passport-koa-bearer-fail/src/config/config.default.ts
  packages/passport/test/fixtures/passport-koa-bearer-fail/src/configuration.ts
  packages/passport/test/fixtures/passport-koa-bearer-fail/src/controller/test.controller.ts
  packages/passport/test/index.test.ts
Labels: pr: polish

#3671 fix: use bull logger when queue emit error
  packages/bull/src/framework.ts
Labels: pr: polish
