Repository midwayjs/midway, pull requests merged in 2025-01, with the labels that each got.

#4257 feat: add package bullmq
  packages/bull/test/fixtures/base-app/src/task/limit.task.ts
  packages/bullmq/CHANGELOG.md
  packages/bullmq/README.md
  packages/bullmq/index.d.ts
  packages/bullmq/jest.config.js
  packages/bullmq/jest.setup.js
  packages/bullmq/package.json
  packages/bullmq/src/config/config.default.ts
  packages/bullmq/src/configuration.ts
  packages/bullmq/src/constants.ts
  packages/bullmq/src/decorator.ts
  packages/bullmq/src/framework.ts
  packages/bullmq/src/index.ts
  packages/bullmq/src/interface.ts
  packages/bullmq/test/fixtures/base-app/package.json
  packages/bullmq/test/fixtures/base-app/src/configuration.ts
  packages/bullmq/test/fixtures/base-app/src/task/hello.task.ts
  packages/bullmq/test/fixtures/base-app/src/task/limit.task.ts
  packages/bullmq/test/fixtures/base-app/src/task/queue.task.ts
  packages/bullmq/test/index.test.ts
  packages/bullmq/tsconfig.json
  packages/bullmq/typedoc.json
Labels: pr: polish

#4231 refactor: axios component
  packages/axios/src/config.default.ts
  packages/axios/src/configuration.ts
  packages/axios/src/http-service.factory.ts
  packages/axios/src/http-service.ts
  packages/axios/src/index.ts
  packages/axios/src/interface.ts
  packages/axios/test/fixtures/base-app/package.json
  packages/axios/test/fixtures/base-app/src/configuration.ts
  packages/axios/test/index.test.ts
Labels: pr: maintenance

#4262 feat: support custom data source
  packages/core/src/interface.ts
  packages/typeorm/src/dataSourceManager.ts
Labels: pr: polish

#4261 refactor: bullmq
  packages/bull-board/index.d.ts
  packages/bull-board/package.json
  packages/bull-board/src/board.middleware.ts
  packages/bull-board/src/configuration.ts
  packages/bull-board/src/interface.ts
  packages/bull-board/test/fixtures/base-app-bullmq/package.json
  packages/bull-board/test/fixtures/base-app-bullmq/src/configuration.ts
  packages/bull-board/test/fixtures/base-app-bullmq/src/task/queue.task.ts
  packages/bull-board/test/fixtures/base-app-express/src/configuration.ts
  packages/bull-board/test/fixtures/base-app-koa/src/configuration.ts
  packages/bull-board/test/index.test.ts
  packages/bullmq/CHANGELOG.md
  packages/bullmq/index.d.ts
  packages/bullmq/package.json
  packages/bullmq/src/config/config.default.ts
  packages/bullmq/src/configuration.ts
  packages/bullmq/src/constants.ts
  packages/bullmq/src/decorator.ts
  packages/bullmq/src/framework.ts
  packages/bullmq/src/index.ts
  packages/bullmq/src/interface.ts
  packages/bullmq/test/fixtures/base-app/src/configuration.ts
  packages/bullmq/test/fixtures/base-app/src/task/hello.task.ts
  packages/bullmq/test/fixtures/base-app/src/task/limit.task.ts
  packages/bullmq/test/index.test.ts
  site/docs/extensions/bullmq.md
  site/docs/sidebars.json
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/bullmq.md
Labels: pr: polish

#4263 fix(swagger): correct typo from 'text/plan' to 'text/plain'
  packages/swagger/src/swaggerExplorer.ts
Labels: pr: bug fix

#4271 fix: KafkaProducerFactory not init from decorator
  packages/kafka/src/configuration.ts
Labels: pr: bug fix

#4278 feat: add custom axios config typings merge
  .github/workflows/nodejs.yml
  packages/axios/index.d.ts
  packages/axios/src/http-service.ts
  packages/axios/src/index.ts
  packages/axios/src/interface.ts
  packages/mqtt/scripts/mosquitto.conf
  packages/mqtt/scripts/start.sh
  packages/mqtt/test/fixtures/base-app/src/configuration.ts
  packages/mqtt/test/index.test.ts
  site/docs/extensions/axios.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/axios.md
Labels: pr: polish
