Repository midwayjs/midway, pull requests merged in 2025-07, with the labels that each got.

#4359 docs: update the wrong spelling of DefaultConfig
  site/docs/esm.md
  site/i18n/en/docusaurus-plugin-content-docs/current/esm.md
Labels: pr: documentation

#4360 feat: add ws upgrade handler
  packages/ws/src/framework.ts
  packages/ws/src/interface.ts
  packages/ws/test/fixtures/base-app-upgrade-auth/package.json
  packages/ws/test/fixtures/base-app-upgrade-auth/src/configuration.ts
  packages/ws/test/fixtures/base-app-upgrade-auth/src/socket.ts
  packages/ws/test/index.test.ts
  packages/ws/test/utils.ts
  site/docs/extensions/ws.md
  site/i18n/en/docusaurus-plugin-content-docs/current/extensions/ws.md
Labels: pr: polish

#4364 fix: heartbeat does not take effect in koa scenario
  packages/ws/package.json
  packages/ws/src/framework.ts
  packages/ws/test/index.test.ts
Labels: pr: bug fix

#4361 breaking: upgrade cron to 3.5.0, support waitForComplete
  packages/cron/package.json
  packages/cron/src/framework.ts
  packages/cron/src/interface.ts
Labels: pr: polish
